/* ============================================================================
   ANEXO — DDL PROPOSTA DO SIADL (modelo físico ideal)
   PSI nº 15358 — Estudo de Caso do Sistema de Atendimento Digital — SIADL
   SGBD: Microsoft SQL Server 2025 | Nomenclatura: TE074/Anexo II (prefixos
   de classe NU_, NO_, DT_, DH_, VR_, IC_, CO_, DE_) | Prefixo de sistema
   ilustrativo: SDL
   Decisões aplicadas (seções 4.1–4.8 da PT): DATETIME2 no lugar de TIMESTAMP;
   domínios TINYINT; particionamento mensal alinhado nas 4 tabelas massivas;
   compressão ROW (quente) / PAGE (morno/frio); PK composta (data+id) nas
   massivas; índices cobertos e filtrados; colunas de auditoria; temporal
   table para auditoria de LIMITE_CONTA; RCSI no banco.
   ============================================================================ */

--------------------------------------------------------------------------------
-- 0. CONFIGURAÇÃO DO BANCO
--------------------------------------------------------------------------------
ALTER DATABASE SIADL SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;
-- Pré-requisito: dimensionamento de tempdb/version store validado em homologação

--------------------------------------------------------------------------------
-- 1. INFRAESTRUTURA DE PARTICIONAMENTO (rolling window mensal)
--------------------------------------------------------------------------------
CREATE PARTITION FUNCTION PF_MENSAL (DATETIME2(3))
AS RANGE RIGHT FOR VALUES
('2026-01-01','2026-02-01','2026-03-01','2026-04-01','2026-05-01','2026-06-01',
 '2026-07-01','2026-08-01','2026-09-01','2026-10-01','2026-11-01','2026-12-01',
 '2027-01-01');

-- Opção A (simples): todas as partições em um filegroup
CREATE PARTITION SCHEME PS_MENSAL AS PARTITION PF_MENSAL ALL TO ([FG_DADOS]);

-- Opção B (recomendada p/ ciclo de vida): filegroups nomeados por período
CREATE PARTITION SCHEME PS_MENSAL_FG AS PARTITION PF_MENSAL
TO (FG_HIST,
    FG_2026_01, FG_2026_02, FG_2026_03, FG_2026_04, FG_2026_05, FG_2026_06,
    FG_2026_07, FG_2026_08, FG_2026_09, FG_2026_10, FG_2026_11, FG_2026_12,
    FG_2027_01);

--------------------------------------------------------------------------------
-- 2. TABELAS DE DOMÍNIO (governadas pelo AD; substituem VARCHAR livres)
--------------------------------------------------------------------------------
CREATE TABLE SDL_CANAL (
  NU_CANAL            TINYINT      NOT NULL,
  NO_CANAL            VARCHAR(80)  NOT NULL,
  CO_TIPO_CANAL       TINYINT      NOT NULL,
  IC_SITUACAO_CANAL   BIT          NOT NULL CONSTRAINT DF_CANAL_SIT DEFAULT 1,
  CONSTRAINT PK_SDL_CANAL PRIMARY KEY CLUSTERED (NU_CANAL),
  CONSTRAINT UQ_SDL_CANAL_NOME UNIQUE (NO_CANAL)
);

CREATE TABLE SDL_SITUACAO_CLIENTE     (CO_SITUACAO_CLIENTE     TINYINT NOT NULL CONSTRAINT PK_SDL_SIT_CLIENTE     PRIMARY KEY, NO_SITUACAO_CLIENTE     VARCHAR(30) NOT NULL);
CREATE TABLE SDL_SEGMENTO_CLIENTE     (CO_SEGMENTO_CLIENTE     TINYINT NOT NULL CONSTRAINT PK_SDL_SEG_CLIENTE     PRIMARY KEY, NO_SEGMENTO_CLIENTE     VARCHAR(30) NOT NULL);
CREATE TABLE SDL_SITUACAO_CONTA       (CO_SITUACAO_CONTA       TINYINT NOT NULL CONSTRAINT PK_SDL_SIT_CONTA       PRIMARY KEY, NO_SITUACAO_CONTA       VARCHAR(30) NOT NULL);
CREATE TABLE SDL_TIPO_CONTA           (CO_TIPO_CONTA           TINYINT NOT NULL CONSTRAINT PK_SDL_TIPO_CONTA      PRIMARY KEY, NO_TIPO_CONTA           VARCHAR(30) NOT NULL);
CREATE TABLE SDL_TIPO_TRANSACAO       (CO_TIPO_TRANSACAO       TINYINT NOT NULL CONSTRAINT PK_SDL_TIPO_TRANSACAO  PRIMARY KEY, NO_TIPO_TRANSACAO       VARCHAR(30) NOT NULL);
CREATE TABLE SDL_SITUACAO_TRANSACAO   (CO_SITUACAO_TRANSACAO   TINYINT NOT NULL CONSTRAINT PK_SDL_SIT_TRANSACAO   PRIMARY KEY, NO_SITUACAO_TRANSACAO   VARCHAR(30) NOT NULL);
CREATE TABLE SDL_TIPO_ATENDIMENTO     (CO_TIPO_ATENDIMENTO     TINYINT NOT NULL CONSTRAINT PK_SDL_TIPO_ATEND      PRIMARY KEY, NO_TIPO_ATENDIMENTO     VARCHAR(30) NOT NULL);
CREATE TABLE SDL_SITUACAO_ATENDIMENTO (CO_SITUACAO_ATENDIMENTO TINYINT NOT NULL CONSTRAINT PK_SDL_SIT_ATEND       PRIMARY KEY, NO_SITUACAO_ATENDIMENTO VARCHAR(30) NOT NULL);
CREATE TABLE SDL_PRIORIDADE           (CO_PRIORIDADE           TINYINT NOT NULL CONSTRAINT PK_SDL_PRIORIDADE      PRIMARY KEY, NO_PRIORIDADE           VARCHAR(30) NOT NULL);
CREATE TABLE SDL_TIPO_LIMITE          (CO_TIPO_LIMITE          TINYINT NOT NULL CONSTRAINT PK_SDL_TIPO_LIMITE     PRIMARY KEY, NO_TIPO_LIMITE          VARCHAR(30) NOT NULL);
CREATE TABLE SDL_ORIGEM_EVENTO        (CO_ORIGEM_EVENTO        TINYINT NOT NULL CONSTRAINT PK_SDL_ORIGEM_EVENTO   PRIMARY KEY, NO_ORIGEM_EVENTO        VARCHAR(30) NOT NULL);
CREATE TABLE SDL_TIPO_INTERACAO       (CO_TIPO_INTERACAO       TINYINT NOT NULL CONSTRAINT PK_SDL_TIPO_INTERACAO  PRIMARY KEY, NO_TIPO_INTERACAO       VARCHAR(30) NOT NULL);

--------------------------------------------------------------------------------
-- 3. DADOS MESTRES
--------------------------------------------------------------------------------
-- Generalização PF×PJ implementada em tabela única (divergência nº 3, seção 5)
CREATE TABLE SDL_CLIENTE (
  NU_CLIENTE                 INT           NOT NULL IDENTITY,
  NO_CLIENTE                 VARCHAR(150)  NOT NULL,
  NU_CPF_CNPJ                BIGINT        NOT NULL,
  IC_TIPO_PESSOA             CHAR(1)       NOT NULL,           -- F = física / J = jurídica
  DT_NASCIMENTO              DATE          NULL,               -- específico PF
  CO_NATUREZA_JURIDICA       SMALLINT      NULL,               -- específico PJ
  DH_CADASTRO                DATETIME2(3)  NOT NULL,           -- era TIMESTAMP: corrigido
  CO_SITUACAO_CLIENTE        TINYINT       NOT NULL,
  CO_SEGMENTO_CLIENTE        TINYINT       NOT NULL,
  DH_INCLUSAO_REGISTRO       DATETIME2(3)  NOT NULL CONSTRAINT DF_CLIENTE_INCL DEFAULT SYSDATETIME(),
  DH_ALTERACAO_REGISTRO      DATETIME2(3)  NULL,
  CO_USUARIO_ULTIMA_ALTERACAO VARCHAR(30)  NULL,
  VS_CONTROLE_CONCORRENCIA   ROWVERSION,                        -- uso legítimo: optimistic locking
  CONSTRAINT PK_SDL_CLIENTE PRIMARY KEY CLUSTERED (NU_CLIENTE),
  CONSTRAINT UQ_SDL_CLIENTE_CPF_CNPJ UNIQUE (NU_CPF_CNPJ),
  CONSTRAINT FK_SDL_CLIENTE_SITUACAO FOREIGN KEY (CO_SITUACAO_CLIENTE) REFERENCES SDL_SITUACAO_CLIENTE (CO_SITUACAO_CLIENTE),
  CONSTRAINT FK_SDL_CLIENTE_SEGMENTO FOREIGN KEY (CO_SEGMENTO_CLIENTE) REFERENCES SDL_SEGMENTO_CLIENTE (CO_SEGMENTO_CLIENTE),
  CONSTRAINT CK_SDL_CLIENTE_TIPO CHECK (IC_TIPO_PESSOA IN ('F','J')),
  -- CHECKs condicionais da generalização exclusiva (salvaguarda da divergência nº 3)
  CONSTRAINT CK_SDL_CLIENTE_PF CHECK (IC_TIPO_PESSOA <> 'F' OR CO_NATUREZA_JURIDICA IS NULL),
  CONSTRAINT CK_SDL_CLIENTE_PJ CHECK (IC_TIPO_PESSOA <> 'J' OR DT_NASCIMENTO IS NULL)
) WITH (DATA_COMPRESSION = PAGE);

CREATE TABLE SDL_CONTA (
  NU_CONTA                   BIGINT        NOT NULL IDENTITY,
  NU_CLIENTE                 INT           NOT NULL,
  NU_CONTA_NEGOCIAL          VARCHAR(30)   NOT NULL,
  CO_TIPO_CONTA              TINYINT       NOT NULL,
  DT_ABERTURA                DATE          NOT NULL,            -- era TIMESTAMP: corrigido
  CO_SITUACAO_CONTA          TINYINT       NOT NULL,
  DH_INCLUSAO_REGISTRO       DATETIME2(3)  NOT NULL CONSTRAINT DF_CONTA_INCL DEFAULT SYSDATETIME(),
  DH_ALTERACAO_REGISTRO      DATETIME2(3)  NULL,
  CO_USUARIO_ULTIMA_ALTERACAO VARCHAR(30)  NULL,
  CONSTRAINT PK_SDL_CONTA PRIMARY KEY CLUSTERED (NU_CONTA),
  CONSTRAINT UQ_SDL_CONTA_NEGOCIAL UNIQUE (NU_CONTA_NEGOCIAL),
  CONSTRAINT FK_SDL_CONTA_CLIENTE  FOREIGN KEY (NU_CLIENTE)        REFERENCES SDL_CLIENTE (NU_CLIENTE),
  CONSTRAINT FK_SDL_CONTA_TIPO     FOREIGN KEY (CO_TIPO_CONTA)     REFERENCES SDL_TIPO_CONTA (CO_TIPO_CONTA),
  CONSTRAINT FK_SDL_CONTA_SITUACAO FOREIGN KEY (CO_SITUACAO_CONTA) REFERENCES SDL_SITUACAO_CONTA (CO_SITUACAO_CONTA)
) WITH (DATA_COMPRESSION = PAGE);

CREATE NONCLUSTERED INDEX IX_SDL_CONTA_CLIENTE
  ON SDL_CONTA (NU_CLIENTE) INCLUDE (NU_CONTA_NEGOCIAL, CO_TIPO_CONTA, CO_SITUACAO_CONTA);

--------------------------------------------------------------------------------
-- 4. TRANSACIONAIS MASSIVAS (particionadas, PK composta alinhada — Alternativa A)
--------------------------------------------------------------------------------
CREATE TABLE SDL_TRANSACAO (
  NU_TRANSACAO           BIGINT        NOT NULL IDENTITY,
  NU_CONTA               BIGINT        NOT NULL,
  NU_CANAL               TINYINT       NOT NULL,
  DH_TRANSACAO           DATETIME2(3)  NOT NULL,               -- era TIMESTAMP: corrigido
  VR_TRANSACAO           DECIMAL(17,2) NOT NULL,
  CO_TIPO_TRANSACAO      TINYINT       NOT NULL,
  CO_SITUACAO_TRANSACAO  TINYINT       NOT NULL,               -- estado corrente (trilha no histórico)
  NU_TRANSACAO_ORIGINAL  BIGINT        NULL,                   -- vínculo do estorno (seção 4.6, abordagem A)
  DH_INCLUSAO_REGISTRO   DATETIME2(3)  NOT NULL CONSTRAINT DF_TRANSACAO_INCL DEFAULT SYSDATETIME(),
  CONSTRAINT PK_SDL_TRANSACAO PRIMARY KEY CLUSTERED (DH_TRANSACAO, NU_TRANSACAO)
      ON PS_MENSAL (DH_TRANSACAO),
  CONSTRAINT FK_SDL_TRANSACAO_CONTA    FOREIGN KEY (NU_CONTA)              REFERENCES SDL_CONTA (NU_CONTA),
  CONSTRAINT FK_SDL_TRANSACAO_CANAL    FOREIGN KEY (NU_CANAL)              REFERENCES SDL_CANAL (NU_CANAL),
  CONSTRAINT FK_SDL_TRANSACAO_TIPO     FOREIGN KEY (CO_TIPO_TRANSACAO)     REFERENCES SDL_TIPO_TRANSACAO (CO_TIPO_TRANSACAO),
  CONSTRAINT FK_SDL_TRANSACAO_SITUACAO FOREIGN KEY (CO_SITUACAO_TRANSACAO) REFERENCES SDL_SITUACAO_TRANSACAO (CO_SITUACAO_TRANSACAO),
  CONSTRAINT CK_SDL_TRANSACAO_VALOR CHECK (VR_TRANSACAO > 0)   -- mantido: estorno é evento próprio
) WITH (DATA_COMPRESSION = ROW  ON PARTITIONS (12 TO 14),      -- quentes (últimos 3 meses)
        DATA_COMPRESSION = PAGE ON PARTITIONS (1 TO 11));      -- mornas/frias

-- Identificador negocial único (apoio às FKs lógicas e consultas por id)
CREATE UNIQUE NONCLUSTERED INDEX UX_SDL_TRANSACAO_NU
  ON SDL_TRANSACAO (NU_TRANSACAO, DH_TRANSACAO)
  ON PS_MENSAL (DH_TRANSACAO);

-- Extrato por conta e período (consulta crítica nº 1)
CREATE NONCLUSTERED INDEX IX_SDL_TRANSACAO_CONTA_DATA
  ON SDL_TRANSACAO (NU_CONTA, DH_TRANSACAO DESC)
  INCLUDE (VR_TRANSACAO, CO_TIPO_TRANSACAO, CO_SITUACAO_TRANSACAO)
  ON PS_MENSAL (DH_TRANSACAO);

CREATE TABLE SDL_TRANSACAO_HISTORICO (
  NU_TRANSACAO_HISTORICO BIGINT        NOT NULL IDENTITY,
  NU_TRANSACAO           BIGINT        NOT NULL,
  DH_EVENTO              DATETIME2(3)  NOT NULL,               -- era TIMESTAMP: corrigido
  CO_SITUACAO_ANTERIOR   TINYINT       NULL,
  CO_SITUACAO_NOVA       TINYINT       NOT NULL,
  CO_ORIGEM_EVENTO       TINYINT       NOT NULL,
  CONSTRAINT PK_SDL_TRANSACAO_HISTORICO
      PRIMARY KEY CLUSTERED (DH_EVENTO, NU_TRANSACAO_HISTORICO) ON PS_MENSAL (DH_EVENTO),
  CONSTRAINT FK_SDL_TRH_ORIGEM FOREIGN KEY (CO_ORIGEM_EVENTO) REFERENCES SDL_ORIGEM_EVENTO (CO_ORIGEM_EVENTO)
) WITH (DATA_COMPRESSION = PAGE);                              -- append-only: PAGE integral

-- Trilha de uma transação (consulta crítica nº 5)
CREATE NONCLUSTERED INDEX IX_SDL_TRH_TRANSACAO
  ON SDL_TRANSACAO_HISTORICO (NU_TRANSACAO, DH_EVENTO)
  INCLUDE (CO_SITUACAO_ANTERIOR, CO_SITUACAO_NOVA, CO_ORIGEM_EVENTO)
  ON PS_MENSAL (DH_EVENTO);

CREATE TABLE SDL_ATENDIMENTO (
  NU_ATENDIMENTO          BIGINT        NOT NULL IDENTITY,
  NU_CLIENTE              INT           NOT NULL,
  NU_CANAL                TINYINT       NOT NULL,             -- era VARCHAR(30) livre: agora FK de domínio
  DH_ABERTURA             DATETIME2(3)  NOT NULL,             -- era TIMESTAMP: corrigido
  DH_FECHAMENTO           DATETIME2(3)  NULL,
  CO_SITUACAO_ATENDIMENTO TINYINT       NOT NULL,
  CO_PRIORIDADE           TINYINT       NOT NULL,
  DH_INCLUSAO_REGISTRO    DATETIME2(3)  NOT NULL CONSTRAINT DF_ATENDIMENTO_INCL DEFAULT SYSDATETIME(),
  CONSTRAINT PK_SDL_ATENDIMENTO PRIMARY KEY CLUSTERED (DH_ABERTURA, NU_ATENDIMENTO)
      ON PS_MENSAL (DH_ABERTURA),
  CONSTRAINT FK_SDL_ATENDIMENTO_CLIENTE    FOREIGN KEY (NU_CLIENTE)              REFERENCES SDL_CLIENTE (NU_CLIENTE),
  CONSTRAINT FK_SDL_ATENDIMENTO_CANAL      FOREIGN KEY (NU_CANAL)                REFERENCES SDL_CANAL (NU_CANAL),
  CONSTRAINT FK_SDL_ATENDIMENTO_SITUACAO   FOREIGN KEY (CO_SITUACAO_ATENDIMENTO) REFERENCES SDL_SITUACAO_ATENDIMENTO (CO_SITUACAO_ATENDIMENTO),
  CONSTRAINT FK_SDL_ATENDIMENTO_PRIORIDADE FOREIGN KEY (CO_PRIORIDADE)           REFERENCES SDL_PRIORIDADE (CO_PRIORIDADE)
) WITH (DATA_COMPRESSION = PAGE);

-- Histórico de atendimentos por cliente e período (consulta crítica nº 2)
CREATE NONCLUSTERED INDEX IX_SDL_ATENDIMENTO_CLIENTE_DATA
  ON SDL_ATENDIMENTO (NU_CLIENTE, DH_ABERTURA DESC)
  INCLUDE (NU_CANAL, CO_SITUACAO_ATENDIMENTO, CO_PRIORIDADE, DH_FECHAMENTO)
  ON PS_MENSAL (DH_ABERTURA);

-- Índice FILTRADO: fila operacional de atendimentos em aberto (consulta crítica nº 3)
CREATE NONCLUSTERED INDEX IX_SDL_ATENDIMENTO_ABERTOS
  ON SDL_ATENDIMENTO (CO_SITUACAO_ATENDIMENTO, DH_ABERTURA)
  INCLUDE (NU_ATENDIMENTO, NU_CLIENTE, NU_CANAL, CO_PRIORIDADE)
  WHERE DH_FECHAMENTO IS NULL;

CREATE TABLE SDL_INTERACAO_ATENDIMENTO (
  NU_INTERACAO            BIGINT        NOT NULL IDENTITY,
  NU_ATENDIMENTO          BIGINT        NOT NULL,
  CO_TIPO_INTERACAO       TINYINT       NOT NULL,
  DH_INTERACAO            DATETIME2(3)  NOT NULL,              -- era TIMESTAMP: corrigido
  CO_ORIGEM_EVENTO        TINYINT       NOT NULL,
  DE_CONTEUDO_RESUMIDO    VARCHAR(500)  NULL,
  CONSTRAINT PK_SDL_INTERACAO PRIMARY KEY CLUSTERED (DH_INTERACAO, NU_INTERACAO)
      ON PS_MENSAL (DH_INTERACAO),
  CONSTRAINT FK_SDL_INTERACAO_TIPO   FOREIGN KEY (CO_TIPO_INTERACAO) REFERENCES SDL_TIPO_INTERACAO (CO_TIPO_INTERACAO),
  CONSTRAINT FK_SDL_INTERACAO_ORIGEM FOREIGN KEY (CO_ORIGEM_EVENTO)  REFERENCES SDL_ORIGEM_EVENTO (CO_ORIGEM_EVENTO)
) WITH (DATA_COMPRESSION = PAGE);

-- Interações de um atendimento em ordem cronológica
CREATE NONCLUSTERED INDEX IX_SDL_INTERACAO_ATENDIMENTO
  ON SDL_INTERACAO_ATENDIMENTO (NU_ATENDIMENTO, DH_INTERACAO)
  INCLUDE (CO_TIPO_INTERACAO, CO_ORIGEM_EVENTO)
  ON PS_MENSAL (DH_INTERACAO);

--------------------------------------------------------------------------------
-- 5. OPERACIONAIS
--------------------------------------------------------------------------------
CREATE TABLE SDL_DISPOSITIVO_CLIENTE (
  NU_DISPOSITIVO             BIGINT        NOT NULL IDENTITY,
  NU_CLIENTE                 INT           NOT NULL,
  CO_TIPO_DISPOSITIVO        TINYINT       NOT NULL,
  NO_SISTEMA_OPERACIONAL     VARCHAR(30)   NOT NULL,
  CO_DISPOSITIVO             VARCHAR(128)  NOT NULL,           -- identificador técnico (dado sensível: DDM)
  DT_VINCULO                 DATE          NOT NULL,            -- era TIMESTAMP: corrigido
  IC_SITUACAO_DISPOSITIVO    BIT           NOT NULL CONSTRAINT DF_DISPOSITIVO_SIT DEFAULT 1,
  DH_INCLUSAO_REGISTRO       DATETIME2(3)  NOT NULL CONSTRAINT DF_DISPOSITIVO_INCL DEFAULT SYSDATETIME(),
  CONSTRAINT PK_SDL_DISPOSITIVO PRIMARY KEY CLUSTERED (NU_DISPOSITIVO),
  CONSTRAINT UQ_SDL_DISPOSITIVO_CO UNIQUE (CO_DISPOSITIVO),
  CONSTRAINT FK_SDL_DISPOSITIVO_CLIENTE FOREIGN KEY (NU_CLIENTE) REFERENCES SDL_CLIENTE (NU_CLIENTE)
) WITH (DATA_COMPRESSION = PAGE);

CREATE NONCLUSTERED INDEX IX_SDL_DISPOSITIVO_CLIENTE
  ON SDL_DISPOSITIVO_CLIENTE (NU_CLIENTE)
  INCLUDE (CO_TIPO_DISPOSITIVO, IC_SITUACAO_DISPOSITIVO, DT_VINCULO);

CREATE TABLE SDL_LIMITE_CONTA (
  NU_LIMITE_CONTA     BIGINT        NOT NULL IDENTITY,
  NU_CONTA            BIGINT        NOT NULL,
  CO_TIPO_LIMITE      TINYINT       NOT NULL,
  VR_LIMITE           DECIMAL(17,2) NOT NULL CONSTRAINT CK_SDL_LIMITE_VALOR CHECK (VR_LIMITE >= 0),
  DT_INICIO_VIGENCIA  DATE          NOT NULL,                  -- era TIMESTAMP: corrigido (application-time)
  DT_FIM_VIGENCIA     DATE          NULL,                      -- NULL = vigente
  VS_CONTROLE_CONCORRENCIA ROWVERSION,
  CONSTRAINT PK_SDL_LIMITE_CONTA PRIMARY KEY CLUSTERED (NU_LIMITE_CONTA),
  CONSTRAINT FK_SDL_LIMITE_CONTA FOREIGN KEY (NU_CONTA)       REFERENCES SDL_CONTA (NU_CONTA),
  CONSTRAINT FK_SDL_LIMITE_TIPO  FOREIGN KEY (CO_TIPO_LIMITE) REFERENCES SDL_TIPO_LIMITE (CO_TIPO_LIMITE),
  CONSTRAINT CK_SDL_LIMITE_VIGENCIA CHECK (DT_FIM_VIGENCIA IS NULL OR DT_FIM_VIGENCIA > DT_INICIO_VIGENCIA)
) WITH (DATA_COMPRESSION = PAGE);

-- Regra temporal aplicada no banco: no máximo UM limite vigente por conta+tipo
-- (a não sobreposição entre vigências históricas é garantida por validação
--  transacional na gravação + conciliação periódica — ver seção 4.5 da PT)
CREATE UNIQUE NONCLUSTERED INDEX IX_SDL_LIMITE_VIGENTE
  ON SDL_LIMITE_CONTA (NU_CONTA, CO_TIPO_LIMITE)
  WHERE DT_FIM_VIGENCIA IS NULL;

-- Auditoria sistêmica (system-time) complementar à vigência negocial (TE074 3.2.7)
ALTER TABLE SDL_LIMITE_CONTA ADD
  DH_INICIO_SISTEMA DATETIME2(7) GENERATED ALWAYS AS ROW START HIDDEN
      CONSTRAINT DF_LIMITE_SYSSTART DEFAULT SYSUTCDATETIME() NOT NULL,
  DH_FIM_SISTEMA    DATETIME2(7) GENERATED ALWAYS AS ROW END HIDDEN
      CONSTRAINT DF_LIMITE_SYSEND   DEFAULT CONVERT(DATETIME2(7),'9999-12-31 23:59:59.9999999') NOT NULL,
  PERIOD FOR SYSTEM_TIME (DH_INICIO_SISTEMA, DH_FIM_SISTEMA);

ALTER TABLE SDL_LIMITE_CONTA
  SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.SDL_LIMITE_CONTA_HISTORICO,
                               DATA_COMPRESSION = PAGE));

--------------------------------------------------------------------------------
-- 6. ESTATÍSTICAS E MANUTENÇÃO (política — exemplos)
--------------------------------------------------------------------------------
-- Estatísticas incrementais por partição nas tabelas massivas
ALTER DATABASE SIADL SET AUTO_CREATE_STATISTICS ON (INCREMENTAL = ON);

-- Rebuild online e resumível por partição (exemplo — executado pela automação de manutenção)
ALTER INDEX PK_SDL_TRANSACAO ON SDL_TRANSACAO
  REBUILD PARTITION = 14
  WITH (ONLINE = ON, RESUMABLE = ON, MAX_DURATION = 60 MINUTES);

-- Query Store para detecção de regressão de planos
ALTER DATABASE SIADL SET QUERY_STORE = ON
  (OPERATION_MODE = READ_WRITE, QUERY_CAPTURE_MODE = AUTO);
